### ISSUE TITLE
Fix/implement failing tests

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#68]
Mentioned in #20 , fix the following tests before setting up CI.

```
1) util
       external functions
         createJSONResponseObject
           should have a status of 'error' if undefined passed as status:
     AssertionError [ERR_ASSERTION]: undefined === 'error'
      at Context.<anonymous> (test/util_test.js:98:24)

  2) util
       external functions
         sanitizeText
           should sanitize input text:
     AssertionError [ERR_ASSERTION]: Not implemented
      at Context.<anonymous> (test/util_test.js:107:24)

  3) util
       external functions
         sanitizeText
           should return empty string if empty string passed in:
     AssertionError [ERR_ASSERTION]: Not implemented
      at Context.<anonymous> (test/util_test.js:110:24)

  4) util
       external functions
         sanitizeText
           should return undefined if undefined passed in:
     AssertionError [ERR_ASSERTION]: Not implemented
      at Context.<anonymous> (test/util_test.js:113:24)

  5) util
       external functions
         escapeOutput
           should escape output text:
     AssertionError [ERR_ASSERTION]: Not implemented
      at Context.<anonymous> (test/util_test.js:118:24)

  6) util
       external functions
         escapeOutput
           should return empty string if empty string passed in:
     AssertionError [ERR_ASSERTION]: Not implemented
      at Context.<anonymous> (test/util_test.js:121:24)

  7) util
       external functions
         escapeOutput
           should return undefined if undefined passed in:
     AssertionError [ERR_ASSERTION]: Not implemented
      at Context.<anonymous> (test/util_test.js:124:24)
```

**Comment by Coteh** [comment]
Addressed in #91.
